### PR TITLE
Added downvote options

### PR DESCRIPTION
**Pull request by thijsdamen**
Added downvote option to main screen.

Downvoting mimics behaviour from poetempest.com, by voting "none" for both it's prefix and suffix on a map.

### CODE REVIEW

**Comment by thijsdamen** [comment]
Sorry for closing the first PR. Some project files came along I wanted to prevent.

Basically, this adds a downvote button next to the upvote button. Allowing users to downvote a map as they can on poetempest.com, downvoting votes for "none", "none" on the map, the same as poetempest.com does when clicking the downvote button.

As said in the previous PR. I never coded in this language so please double check whatever I did for mistakes.

**Comment by pajlada** [comment]
Looks good at a quick glance, however are you sure this mimics the downvote behaviour of poetempest.com? From what I recall, pressing the downvote button would force you to correct with the right tempests, not automatically reporting it as None/None.

**Comment by thijsdamen** [comment]
Updated.

You were right, the javascript only showed it was voting. However it would show the prefix-suffix selector.

Update the pullrequest. It now shows a red message for the user t o enter the correct pre and suffix.

**Comment by pajlada** [comment]
Looks good to me!

**Pull request merged**
